// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MatrixDbContext))]
    [Migration("20251120160827_Second-Commit")]
    partial class SecondCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4b1f8b4-5b4a-4b4a-8b4a-5b4a4b4a4b4a"),
                            DateJoined = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "superAdmin@gmail.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "$2a$12$EGOawab0.yM2V9ZqlNwuxuDRiPQ1nsIM9M4rsfWwqzNzy1Y8qBl1u",
                            Role = 1,
                            UserName = "Superadmin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentBatchId")
                        .HasColumnType("integer");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentBatchId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Domain.Entities.AssessmentBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LearnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamMemberID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearnerID");

                    b.HasIndex("SkillId");

                    b.HasIndex("TeamMemberID");

                    b.ToTable("AssessmentBatches");
                });

            modelBuilder.Entity("Domain.Entities.AssessmentOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.ToTable("AssessmentOptions");
                });

            modelBuilder.Entity("Domain.Entities.AssessmentResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssessmentBatchId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AssignedSkillId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImprovementPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LearnerID")
                        .HasColumnType("uuid");

                    b.Property<int>("NoOfCorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<int>("NoOfUnansweredQuestions")
                        .HasColumnType("integer");

                    b.Property<int>("NoOfWrongAnswers")
                        .HasColumnType("integer");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamMemberID")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentBatchId")
                        .IsUnique();

                    b.HasIndex("AssignedSkillId");

                    b.HasIndex("LearnerID");

                    b.HasIndex("SkillId");

                    b.HasIndex("TeamMemberID");

                    b.ToTable("AssessmentResults");
                });

            modelBuilder.Entity("Domain.Entities.AssignedBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedSkillId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAwarded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LearnerID")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedSkillId");

                    b.HasIndex("LearnerID");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("AssignedBadges");
                });

            modelBuilder.Entity("Domain.Entities.AssignedCareerPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("AssignedCareerPaths");
                });

            modelBuilder.Entity("Domain.Entities.AssignedSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("SkillId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("AssignedSkills");
                });

            modelBuilder.Entity("Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("Domain.Entities.CareerPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CareerPaths");
                });

            modelBuilder.Entity("Domain.Entities.ImprovementPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentResultId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateGenerated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FocusArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GeneratedSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentResultId")
                        .IsUnique();

                    b.ToTable("ImprovementPlans");
                });

            modelBuilder.Entity("Domain.Entities.Learner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Learners");
                });

            modelBuilder.Entity("Domain.Entities.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<int>("Roles")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Domain.Entities.RecommendedResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ImprovementPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResourseType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImprovementPlanId");

                    b.ToTable("RecommendedResources");
                });

            modelBuilder.Entity("Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Domain.Entities.UserResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssessmentBatchId")
                        .HasColumnType("integer");

                    b.Property<int>("AssessmentQuestionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SelectedOptionId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentBatchId");

                    b.HasIndex("AssessmentQuestionId");

                    b.HasIndex("LearnerId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("UserResponses");
                });

            modelBuilder.Entity("Domain.Entities.Assessment", b =>
                {
                    b.HasOne("Domain.Entities.AssessmentBatch", "AssessmentBatch")
                        .WithMany("Assessments")
                        .HasForeignKey("AssessmentBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentBatch");
                });

            modelBuilder.Entity("Domain.Entities.AssessmentBatch", b =>
                {
                    b.HasOne("Domain.Entities.Learner", "Learner")
                        .WithMany("AssessmentBatches")
                        .HasForeignKey("LearnerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.AssignedSkill", "AssignedSkill")
                        .WithMany("AssessmentBatches")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("AssessmentBatches")
                        .HasForeignKey("TeamMemberID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedSkill");

                    b.Navigation("Learner");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Domain.Entities.AssessmentOptions", b =>
                {
                    b.HasOne("Domain.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentOptions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("Domain.Entities.AssessmentResult", b =>
                {
                    b.HasOne("Domain.Entities.AssessmentBatch", "AssessmentBatch")
                        .WithOne("AssessmentResult")
                        .HasForeignKey("Domain.Entities.AssessmentResult", "AssessmentBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AssignedSkill", null)
                        .WithMany("UserCareerPaths")
                        .HasForeignKey("AssignedSkillId");

                    b.HasOne("Domain.Entities.Learner", "Learner")
                        .WithMany("AssessmentResults")
                        .HasForeignKey("LearnerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.AssignedSkill", "Skill")
                        .WithMany("AssessmentResults")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("AssessmentResults")
                        .HasForeignKey("TeamMemberID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssessmentBatch");

                    b.Navigation("Learner");

                    b.Navigation("Skill");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Domain.Entities.AssignedBadge", b =>
                {
                    b.HasOne("Domain.Entities.AssignedSkill", null)
                        .WithMany("Badges")
                        .HasForeignKey("AssignedSkillId");

                    b.HasOne("Domain.Entities.Learner", "Learner")
                        .WithMany("Badges")
                        .HasForeignKey("LearnerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("Badges")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Learner");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Domain.Entities.AssignedCareerPath", b =>
                {
                    b.HasOne("Domain.Entities.Learner", "Learner")
                        .WithMany("LearnerCareerPaths")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("CareerPaths")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Learner");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Domain.Entities.AssignedSkill", b =>
                {
                    b.HasOne("Domain.Entities.Learner", "Learner")
                        .WithMany("LearnerSkills")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Skill", "Skill")
                        .WithMany("AssignedSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("TeamMemberSkills")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Learner");

                    b.Navigation("Skill");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Domain.Entities.ImprovementPlan", b =>
                {
                    b.HasOne("Domain.Entities.AssessmentResult", "AssessmentResult")
                        .WithOne("ImprovementPlan")
                        .HasForeignKey("Domain.Entities.ImprovementPlan", "AssessmentResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentResult");
                });

            modelBuilder.Entity("Domain.Entities.Manager", b =>
                {
                    b.HasOne("Domain.Entities.Organization", "Organization")
                        .WithOne("Manager")
                        .HasForeignKey("Domain.Entities.Manager", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Domain.Entities.RecommendedResource", b =>
                {
                    b.HasOne("Domain.Entities.ImprovementPlan", "ImprovementPlan")
                        .WithMany("RecommendedResources")
                        .HasForeignKey("ImprovementPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImprovementPlan");
                });

            modelBuilder.Entity("Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Domain.Entities.Manager", "Manager")
                        .WithMany("TeamMembers")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Organization", "Organization")
                        .WithMany("TeamMembers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Domain.Entities.UserResponse", b =>
                {
                    b.HasOne("Domain.Entities.AssessmentBatch", "AssessmentBatch")
                        .WithMany()
                        .HasForeignKey("AssessmentBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Assessment", "AssessmentQuestion")
                        .WithMany("UserResponses")
                        .HasForeignKey("AssessmentQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Learner", "Learner")
                        .WithMany("UserResponses")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.AssessmentOptions", "SelectedOption")
                        .WithMany("UserResponses")
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("UserResponses")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssessmentBatch");

                    b.Navigation("AssessmentQuestion");

                    b.Navigation("Learner");

                    b.Navigation("SelectedOption");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Domain.Entities.Assessment", b =>
                {
                    b.Navigation("AssessmentOptions");

                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("Domain.Entities.AssessmentBatch", b =>
                {
                    b.Navigation("AssessmentResult")
                        .IsRequired();

                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("Domain.Entities.AssessmentOptions", b =>
                {
                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("Domain.Entities.AssessmentResult", b =>
                {
                    b.Navigation("ImprovementPlan")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.AssignedSkill", b =>
                {
                    b.Navigation("AssessmentBatches");

                    b.Navigation("AssessmentResults");

                    b.Navigation("Badges");

                    b.Navigation("UserCareerPaths");
                });

            modelBuilder.Entity("Domain.Entities.ImprovementPlan", b =>
                {
                    b.Navigation("RecommendedResources");
                });

            modelBuilder.Entity("Domain.Entities.Learner", b =>
                {
                    b.Navigation("AssessmentBatches");

                    b.Navigation("AssessmentResults");

                    b.Navigation("Badges");

                    b.Navigation("LearnerCareerPaths");

                    b.Navigation("LearnerSkills");

                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("Domain.Entities.Manager", b =>
                {
                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("Domain.Entities.Organization", b =>
                {
                    b.Navigation("Manager")
                        .IsRequired();

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("Domain.Entities.Skill", b =>
                {
                    b.Navigation("AssignedSkills");
                });

            modelBuilder.Entity("Domain.Entities.TeamMember", b =>
                {
                    b.Navigation("AssessmentBatches");

                    b.Navigation("AssessmentResults");

                    b.Navigation("Badges");

                    b.Navigation("CareerPaths");

                    b.Navigation("TeamMemberSkills");

                    b.Navigation("UserResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
